name: Continous Integration

on:
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"

      - uses: pnpm/action-setup@v2
        name: Setup pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Install dependencies
        run: pnpm install

      - name: Build packages
        run: pnpm build

      - name: Test packages
        run: pnpm test

  changes_check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"

      - uses: pnpm/action-setup@v2
        name: Setup pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Install dependencies
        run: pnpm install

      - name: Check for changesets
        run: pnpm changeset status --since=origin/main
