name: Release Packages

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - uses: pnpm/action-setup@v2
        name: Setup pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Set npm config
        run: pnpm config set '//registry.npmjs.org/:_authToken' "${NODE_AUTH_TOKEN}"
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Install dependencies
        run: pnpm install

      - name: Run multi semantic release
        run: pnpm run release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to npm
        run: pnpm -r publish --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
