name: Release Packages

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - uses: pnpm/action-setup@v2
        name: Setup pnpm
        with:
          version: 7
          run_install: false

      - name: Set npm config
        run: pnpm config set '//registry.npmjs.org/:_authToken' "${NODE_AUTH_TOKEN}"
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Install dependencies
        run: pnpm install

      - name: Configure git author
        run: |
          git config user.email "${{vars.RELEASE_AUTHOR_EMAIL}}"
          git config user.name "${{vars.RELEASE_AUTHOR_NAME}}"
          git remote set-url origin https://${{vars.RELEASE_AUTHOR_USERNAME}}:${{secrets.RELEASE_AUTHOR_TOKEN}}@github.com/${{github.repository}}.git

      - name: Run beachball release
        run: pnpm run release publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
